#include "smoke_runner.hpp"
#include "script_runner.hpp"

#include <chrono>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <iostream>
#include <string>
#include <unistd.h>
#include <vector>

namespace fs = std::filesystem;

static std::string find_havel_binary() {
	char self_path[4096] = {};
	ssize_t len = readlink("/proc/self/exe", self_path, sizeof(self_path) - 1);
	if (len > 0) {
		self_path[len] = '\0';
		fs::path self(self_path);
		fs::path havel_path = self.parent_path() / "havel";
		if (fs::exists(havel_path)) return havel_path.string();
	}
	if (const char *env = std::getenv("HAVEL_BIN")) return env;
	return "havel";
}

static std::string find_scripts_root() {
	char self_path[4096] = {};
	ssize_t len = readlink("/proc/self/exe", self_path, sizeof(self_path) - 1);
	if (len > 0) {
		self_path[len] = '\0';
		fs::path self(self_path);
		fs::path root = self.parent_path().parent_path().parent_path();
		if (fs::exists(root / "scripts" / "smoke")) return (root / "scripts").string();
	}
	if (const char *env = std::getenv("HAVEL_SCRIPTS")) return env;
	fs::path cwd = fs::current_path();
	if (fs::exists(cwd / "scripts" / "smoke")) return (cwd / "scripts").string();
	return "scripts";
}

static void print_usage(const char *prog) {
	std::cerr << "usage: " << prog << " [mode] [options] [file...]\n"
		"\n"
		"modes:\n"
		"  (default)       run all tests\n"
		"  --smoke         run bytecode smoke tests (inline, fast)\n"
		"  --scripts       run .hv script tests (smoke + integration + main)\n"
		"  --cpp           run C++ unit tests via ctest\n"
		"  --list          list all test files without running\n"
		"  --all           run everything (smoke + scripts + cpp)\n"
		"\n"
		"options:\n"
		"  --verbose       show script output on failure\n"
		"  --timeout <sec> per-test timeout in seconds (default: 30)\n"
		"  --havel <path>  path to havel binary (default: auto-detect)\n"
		"  --scripts-root  path to scripts/ directory (default: auto-detect)\n"
		"  --dump-bytecode show generated bytecode (smoke mode)\n"
		"  --no-snapshots  disable snapshot artifacts (smoke mode)\n"
		"\n"
		"  <file>          run a single .hv file\n";
}

int main(int argc, char **argv) {
	bool mode_smoke = false;
	bool mode_scripts = false;
	bool mode_cpp = false;
	bool mode_list = false;
	bool mode_all = false;
	bool verbose = false;
	int timeout = 30;
	std::string havel_bin;
	std::string scripts_root;
	std::vector<char *> smoke_args;
	std::vector<std::string> single_files;

	smoke_args.push_back(argv[0]);

	for (int i = 1; i < argc; ++i) {
		std::string arg = argv[i];
		if (arg == "--smoke") { mode_smoke = true; }
		else if (arg == "--scripts") { mode_scripts = true; }
		else if (arg == "--cpp") { mode_cpp = true; }
		else if (arg == "--list") { mode_list = true; }
		else if (arg == "--all") { mode_all = true; }
		else if (arg == "--verbose") { verbose = true; }
		else if (arg == "--timeout" && i + 1 < argc) { timeout = std::atoi(argv[++i]); }
		else if (arg == "--havel" && i + 1 < argc) { havel_bin = argv[++i]; }
		else if (arg == "--scripts-root" && i + 1 < argc) { scripts_root = argv[++i]; }
		else if (arg == "--dump-bytecode" || arg == "--no-snapshots" || arg == "--snapshot-dir") {
			smoke_args.push_back(argv[i]);
			if (arg == "--snapshot-dir" && i + 1 < argc) {
				smoke_args.push_back(argv[++i]);
			}
		}
		else if (arg == "--help" || arg == "-h") { print_usage(argv[0]); return 0; }
		else if (arg[0] != '-') { single_files.push_back(arg); }
		else { std::cerr << "unknown option: " << arg << std::endl; return 1; }
	}

	if (havel_bin.empty()) havel_bin = find_havel_binary();
	if (scripts_root.empty()) scripts_root = find_scripts_root();

	if (!mode_smoke && !mode_scripts && !mode_cpp && !mode_list && !mode_all && single_files.empty()) {
		mode_all = true;
	}

	int failures = 0;

	if (mode_list) {
		auto dirs = hvtest::list_test_dirs(scripts_root);
		return hvtest::list_scripts(dirs);
	}

	if (!single_files.empty()) {
		for (const auto &file : single_files) {
			auto result = hvtest::run_script(havel_bin, file, timeout);
			if (result.passed) {
				std::cout << "[PASS] " << file << " (" << result.elapsed_ms << "ms)" << std::endl;
			} else if (result.timed_out) {
				std::cout << "[FAIL] " << file << " (timeout)" << std::endl;
				failures++;
			} else {
				std::cout << "[FAIL] " << file << " (exit=" << result.exit_code << ")" << std::endl;
				failures++;
			}
		}
		return failures > 0 ? 1 : 0;
	}

	if (mode_all || mode_smoke) {
		std::cout << "=== bytecode smoke ===" << std::endl;
		int smoke_argc = static_cast<int>(smoke_args.size());
		std::vector<char *> smoke_argv(smoke_args.begin(), smoke_args.end());
		failures += hvtest::run_smoke_tests(smoke_argc, smoke_argv.data());
	}

	if (mode_all || mode_scripts) {
		std::cout << "\n=== script tests ===" << std::endl;
		auto dirs = hvtest::list_test_dirs(scripts_root);
		failures += hvtest::run_script_suite(havel_bin, dirs, verbose);
	}

	if (mode_all || mode_cpp) {
		std::cout << "\n=== C++ unit tests ===" << std::endl;
		int ret = std::system("ctest --output-on-failure");
		failures += (ret == 0) ? 0 : 1;
	}

	return failures > 0 ? 1 : 0;
}
