#pragma once
#include "ConfigManager.hpp"
#include "../utils/Logger.hpp"
#include <X11/Xlib.h>
#include <cstdlib>
#include <iostream>

// Forward declarations for Wayland types
#ifdef __WAYLAND__
struct wl_display;
struct wl_registry;
struct wl_output;
struct wl_proxy;

// Forward declarations for Wayland protocols
struct zwlr_gamma_control_manager_v1;
struct zxdg_output_manager_v1;
struct zxdg_output_v1;

// Include Wayland protocol headers if available
#include <wayland-client.h>

// Include generated protocol headers
// These headers are generated by CMake and placed in the build directory
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

// Use the full path to the generated protocol headers
#include "wlr-gamma-control-unstable-v1-client-protocol.h"
#include "xdg-output-unstable-v1-client-protocol.h"

#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
#endif
#include <sstream>
#include <memory>
#include <array>
#include <cmath>
#include <regex>
#include <string>
#include <vector>
#include <thread>
#include <atomic>
#include <chrono>
#include <mutex>
#include <functional>
#include <unordered_map>

using namespace std;
namespace havel {
class BrightnessManager {
public:
    struct RGBColor {
        double red, green, blue;
    };
    struct DayNightSettings {
        double dayBrightness = 1.0;
        double nightBrightness = 0.3;
        int dayTemperature = 6500;    // Kelvin
        int nightTemperature = 3000;  // Kelvin
        
        // Timing (24h format)
        int dayStartHour = 7;    // 7:00 AM
        int nightStartHour = 20; // 8:00 PM
        
        bool autoAdjust = false;
        chrono::minutes checkInterval{5}; // Check every 5 minutes
    };

    BrightnessManager();
    ~BrightnessManager();
    string getMonitor(int index);
    // === BRIGHTNESS OVERLOADS ===
    bool setBrightness(double brightness);  // All monitors
    bool setBrightness(const string& monitor, double brightness);
    bool setBrightness(int monitorIndex, double brightness);
    double getBrightness();
    double getBrightness(const string& monitor);
    double getBrightness(int monitorIndex);
    // === RGB GAMMA OVERLOADS ===
    bool setGammaRGB(double red, double green, double blue);  // All monitors
    bool setGammaRGB(const string& monitor, double red, double green, double blue);
    bool setGammaRGB(int monitorIndex, double red, double green, double blue);
    RGBColor getGammaRGB();
    RGBColor getGammaRGB(const string& monitor);

    // === KELVIN TEMPERATURE OVERLOADS ===
    bool setTemperature(int kelvin);  // All monitors
    bool setTemperature(const string& monitor, int kelvin);
    bool setTemperature(int monitorIndex, int kelvin);
    int getTemperature();
    int getTemperature(int monitorIndex);
    int getTemperature(const string& monitor);

    // === GAMMA ADJUSTMENT OVERLOADS ===
    bool decreaseGamma(int amount);
    bool increaseGamma(int amount);
    bool decreaseGamma(const string& monitor, int amount);
    bool increaseGamma(const string& monitor, int amount);
    bool decreaseGamma(int monitorIndex, int amount);
    bool increaseGamma(int monitorIndex, int amount);
    bool increaseShadowLift(int amount);
    bool increaseShadowLift(const string& monitor, int amount);
    bool increaseShadowLift(int monitorIndex, int amount);
    bool decreaseShadowLift(int amount);
    bool decreaseShadowLift(const string& monitor, int amount);
    bool decreaseShadowLift(int monitorIndex, int amount);
    
    // === SHADOW LIFT OVERLOADS ===
    bool setShadowLift(double lift);  // All monitors, 0.0-4.0
    bool setShadowLift(const string& monitor, double lift);
    bool setShadowLift(int monitorIndex, double lift);
    double getShadowLift();
    double getShadowLift(const string& monitor);
    double getShadowLift(int monitorIndex);

    // === X11 SPECIFIC METHODS ===
    double getCurrentBrightnessX11(const std::string& monitor_name);
    double extractBrightnessFromGammaRamp(XRRCrtcGamma* gamma, const std::string& monitor_name) const;

    // === COMBINED OPERATIONS ===
    bool setBrightnessAndRGB(double brightness, double red, double green, double blue);
    bool setBrightnessAndRGB(const string& monitor, double brightness, double red, double green, double blue);
    bool setBrightnessAndRGB(int monitorIndex, double brightness, double red, double green, double blue);
    
    bool setBrightnessAndTemperature(double brightness, int kelvin);
    bool setBrightnessAndTemperature(const string& monitor, double brightness, int kelvin);
    bool setBrightnessAndTemperature(int monitorIndex, double brightness, int kelvin);

    bool setBrightnessAndShadowLift(double brightness, double shadowLift);
    bool setBrightnessAndShadowLift(const string& monitor, double brightness, double shadowLift);
    bool setBrightnessAndShadowLift(int monitorIndex, double brightness, double shadowLift);

    // === INCREMENT OPERATIONS ===
    bool increaseBrightness(double amount = DEFAULT_BRIGHTNESS_AMOUNT);
    bool increaseBrightness(const string& monitor, double amount = DEFAULT_BRIGHTNESS_AMOUNT);
    bool increaseBrightness(int monitorIndex, double amount);
    bool decreaseBrightness(double amount);
    bool decreaseBrightness(const string& monitor, double amount);
    bool decreaseBrightness(int monitorIndex, double amount);

    bool increaseTemperature(int amount);
    bool increaseTemperature(const string& monitor, int amount);
    bool increaseTemperature(int monitorIndex, int amount);
    bool decreaseTemperature(int amount);
    bool decreaseTemperature(const string& monitor, int amount);
    bool decreaseTemperature(int monitorIndex, int amount);

    // === DAY/NIGHT AUTOMATION ===
    void enableDayNightMode(const DayNightSettings& settings);
    void disableDayNightMode();
    bool isDayNightModeEnabled() const { return dayNightSettings.autoAdjust; }
    
    void setDaySettings(double brightness, int temperature);
    void setNightSettings(double brightness, int temperature);
    void setDayNightTiming(int dayStart, int nightStart);
    
    // Manual day/night switching
    bool switchToDay();   // All monitors
    bool switchToNight(); // All monitors
    bool switchToDay(const string& monitor);
    bool switchToNight(const string& monitor);
    bool switchToDay(int monitorIndex);
    bool switchToNight(int monitorIndex);

    // === UTILITY ===
    vector<string> getConnectedMonitors();
    bool isDay();  // Based on current time and settings
    string primaryMonitor;
    // Constants
    static constexpr double DEFAULT_BRIGHTNESS_AMOUNT = 0.02;
    static constexpr int DEFAULT_TEMP_AMOUNT = 200;
    static constexpr int MIN_TEMPERATURE = 1000;
    static constexpr int MAX_TEMPERATURE = 25000;
    
    private:
    Display* x11_display;
    Window x11_root;
    
    // Wayland specific members
    #ifdef __WAYLAND__
    struct wl_display *wl_display = nullptr;
    struct wl_registry *wl_registry = nullptr;
    struct zwlr_gamma_control_manager_v1 *gamma_control_manager = nullptr;
    struct zxdg_output_manager_v1 *xdg_output_manager = nullptr;

    // Backend initialization
    void initializeWayland();
    #endif
    
    double getBrightnessGamma(const std::string &monitor);
    bool setBrightnessGamma(const std::string &monitor, double brightness);
    // Debug logging helpers
    static void debug(const std::string& message) {
        havel::Logger::getInstance().debug("[BrightnessManager] " + message);
    }
    
    static void error(const std::string& message) {
        havel::Logger::getInstance().error("[BrightnessManager] " + message);
    }
       /**
     * Debug logging with automatic [BrightnessManager] prefix
     * Usage: debug("Monitor {} brightness: {:.3f}", monitor_name, brightness);
     */
    template<typename... Args>
    static void debug(const std::string& format, Args&&... args) {
        havel::Logger::getInstance().debug("[BrightnessManager] " + format, std::forward<Args>(args)...);
    }
    
    template<typename... Args>
    static void info(const std::string& format, Args&&... args) {
        havel::Logger::getInstance().info("[BrightnessManager] " + format, std::forward<Args>(args)...);
    }
    
    template<typename... Args>
    static void warning(const std::string& format, Args&&... args) {
        havel::Logger::getInstance().warning("[BrightnessManager] " + format, std::forward<Args>(args)...);
    }
    
    template<typename... Args>
    static void error(const std::string& format, Args&&... args) {
        havel::Logger::getInstance().error("[BrightnessManager] " + format, std::forward<Args>(args)...);
    }
    
    template<typename... Args>
    static void fatal(const std::string& format, Args&&... args) {
        havel::Logger::getInstance().fatal("[BrightnessManager] " + format, std::forward<Args>(args)...);
    }
    // === KELVIN TO RGB CONVERSION ===

    RGBColor kelvinToRGB(int kelvin) const;
    int rgbToKelvin(const RGBColor& rgb) const;
    
    // === BACKEND IMPLEMENTATIONS ===
    bool setBrightnessXrandr(const string& monitor, double brightness);
    bool setBrightnessXrandr(double brightness);
    double getBrightnessXrandr(const string& monitor);
    double getBrightnessSysfs(const string& monitor);
    
    bool setGammaXrandrRGB(const string& monitor, double red, double green, double blue);
    bool setGammaXrandrRGB(double red, double green, double blue);
    double getGammaXrandr(const string& monitor);
    RGBColor getGammaXrandrRGB(const string& monitor);
    
    bool setBrightnessWayland(const string& monitor, double brightness);
    bool setBrightnessWayland(double brightness);
    
    bool setGammaWaylandRGB(const string& monitor, double red, double green, double blue);
    bool setGammaWaylandRGB(double red, double green, double blue);

    // === DAY/NIGHT AUTOMATION ===
    void dayNightWorkerThread();
    void applyCurrentTimeSettings();
    RGBColor applyShadowLift(const RGBColor& input, double lift);
    bool applyAllSettings(const string &monitor);
    // === STATE ===
    DayNightSettings dayNightSettings;
    
    vector<string> cached_monitors;
    string displayMethod;
    
    // Threading for day/night
    atomic<bool> stopDayNightThread{false};
    unique_ptr<thread> dayNightThread;
    mutex settingsMutex;
    
    // Current state tracking
    map<string, double> brightness;
    map<string, int> temperature;
    vector<string> monitors;
    map<string, RGBColor> gammaRGB;
    map<string, double> shadowLift;
};

} // namespace havel
